### PR TITLE
Consider allowing bastion group security id to be optional

### PR DESCRIPTION
**Pull request by isen-ng**

### CODE REVIEW

**Comment by SiahaanBernard** [comment]
Hi @isen-ng ,
Thanks for the pull request, can you elaborate more why do you want to make the bastion security group id as an optional?

**Comment by isen-ng** [comment]
In the event that I don't have/need a bastion server, I cannot use this module to create RDS instances.

(Please correct me if i'm wrong) bastion servers are used as a auditable jump host to view the data in our RDS cluster or to provision databases and users.

However, so far, I don't have a need to directly view user data on production and all of my provisioning scripts are run through continuous deployment, through the private VPC. So I don't have the need for a bastion host (yet).

Also arguably, adding a new required variable is a breaking changing and the major version should be bumped. Making it optional again (and probably deprecating the current release) will make it a non-breaking change and only the minor version needs to be upgraded.

**Comment by sshvetsov** [comment]
> In the event that I don't have/need a bastion server, I cannot use this module to create RDS instances.
> 
> (Please correct me if i'm wrong) bastion servers are used as a auditable jump host to view the data in our RDS cluster or to provision databases and users.
> 
> However, so far, I don't have a need to directly view user data on production and all of my provisioning scripts are run through continuous deployment, through the private VPC. So I don't have the need for a bastion host (yet).

So if I understand you correctly, you can securely and with audit trail use your CI/CD to:
- create database credentials for users and apps
- modify their privileges
- update schemas
- do data migrations
- troubleshot data issues in your DB

If my interpretation correct, please color me impressed and do tell me more.

If you have no use for DB Bastion you don't actually need to start one. DB Bastion module creates security groups and an empty autoscaling group. There are no costs associated with it, unless you increase the desired capacity of the ASG to launch the bastion. On another hand, however, requiring bastion SG to launch an RDS, sends a (hopefully?) clear message that users are not allowed to connect to the DB directly.

> Also arguably, adding a new required variable is a breaking changing and the major version should be bumped. Making it optional again (and probably deprecating the current release) will make it a non-breaking change and only the minor version needs to be upgraded.

Arguably, you are correct. However, there's also a common convention that versions below 1.0.0 do not strictly follow major/minor conventions and can have breaking changes without a major version bump.

**Comment by isen-ng** [comment]
### create database credentials for users and apps
We use kubernetes (EKS) to host our apps. This means we have access to kubernetes secrets.
When we deploy RDS and EKS using terraform, it is also possible to use terraform to into the RDS root credentials into EKS as a kubernetes secret.

We then use helm to template and deploy our applications, and using the helm templates, we can tell a deployment to do a kubernetes job before installing a deployment. We write a (shared) template to create a new user and a new database for the app we are deploying using the root-credentials and the new db and user credentials are inserted into the kubernetes secrets as well. Then the app is deployed pointing to the new secrets that we have just created.

### update schemas && do data migrations
Since we got no DBAs, this is handled by the app. Whenever the app starts, it ensures that the db schema and data is in the latest state.

### troubleshot data issues in your DB
This is something i am trying to avoid on production systems. Troubleshooting should only happen on staging with private information masked. Coping of data from production to staging should also be automated instead of someone going into a bastion server and typing in a command.

> On another hand, however, requiring bastion SG to launch an RDS, sends a (hopefully?) clear message that users are not allowed to connect to the DB directly.

I agree that this message needs to be strongly sent across and that means that the bastion security group id should be compulsory. 

I think my only final grievance is that I still am unable to create a bastion server from the traveloka/terraform-aws-tvlk-bastion repo

**Comment by isen-ng** [comment]
Since I also agree that bastion server security group id should be compulsory, closing this PR.

**Comment by sshvetsov** [comment]
I would still advise against using the RDS root credentials to "create a new user and a new database". Better create a Postgres user/creds dedicated for that specific purpose (let's call it "dba") with just enough permissions to create users/dbs/grants, while keeping root password safe for emergencies (e.g. when "dba" creds are leaked and need to be quickly revoked by another privileged user).

> I think my only final grievance is that I still am unable to create a bastion server from the traveloka/terraform-aws-tvlk-bastion repo.

Have you already created an issue detailing the problem you're having?

> I guess I'll have to use an older version of this terraform script (before bastion was added) before I figure out how to create a bastion server.

Are you saying that instead of helping us help you solve an issue you and possible others have with this module by properly reporting it, you would rather use an outdated, unsupported version, effectively helping only yourself? I sincerely hope that I'm misunderstanding this.

**Comment by isen-ng** [comment]
> Have you already created an issue detailing the problem you're having?

Yes I have, however, I'm now stuck doing something else until I have some time to get back to that.

> Are you saying that instead of helping us help you solve an issue you and possible others have with this module by properly reporting it, you would rather use an outdated, unsupported version, effectively helping only yourself? I sincerely hope that I'm misunderstanding this

I'm sorry if I sounded that way but I do not intend for it to be that way. I have raised the issue with Bernard (and the github repo) and I hope to have this solved for the long run. Before that, I have to downgrade to the version of this repo that does require bastion servers.

**Pull request closed without merging**
